### ISSUE TITLE
OTR_TOPICS has no effect

### ISSUE THREAD

**Issue by Th3H0ff** [owntracks/docker-recorder#86] opened 2024-10-30 08:10 UTC
Greetings
I'm trying to get owntracks-recorder to target another topic in my local MQTT and not use owntracks/#. It doesn't matter if I use OTR_TOPICS as an enviroment variable or in the recorder.conf, it simply isn't processed and recoder processes the "default" topic according to the logs.
+ Using storage at /store with precision 7
+ Configured with revgeo=true and geokey: nil
+ TZDATADB is at /config/timezone16.bin: ENOENT
+ Subscribing to owntracks/# (qos=2)

My owntracks-recorder version is 0.9.9.

My docker-compose
```
version: '3'
services:

  owntrack-backend:
    image: owntracks/recorder
    container_name: owntrack-backend
    ports:
      - 8085:8085
    volumes:
      - /home/owntrack/config:/config
      - /home/owntrack/store:/store
    restart: unless-stopped
```

My recorder.conf
```
OTR_TOPICS="msh/EU_868/2/json/#"
OTR_HTTPHOST="0.0.0.0"
OTR_HTTPPORT="8085"
OTR_HOST="172.16.80.2"
OTR_PORT="1883"
OTR_USER="***"
OTR_PASS="****"
```

Is OTR_TOPICS deprecated somehow or am I missing something else?

**Comment by jpmens** [comment] 2024-10-30 08:26
The setting isn't deprecated and works with vanilla Recorder:

```console
$ OTR_TOPICS="msh/EU_868/2/json/#" ./ot-recorder -S JP --port 1883
Oct 30 09:20:50  ot-recorder[6149] <Debug>: version 0.9.9 starting with STORAGEDIR=JP
...
Oct 30 08:20:50  ot-recorder[6149] <Debug>: Subscribing to msh/EU_868/2/json/# (qos=2)
```

Have you changed some other setting in your configuration to verify `recorder.conf` is actually being used?

Incidentally I note you are trying to subscribe to a topic branch which does not begin with the string `owntracks/`, and while we see that works, I fear the Recorder won't do with that what you expect it to.

A good many years ago we decided the topic branch had to start with `owntracks/`, so I really don't know whether this will work for you -- I doubt it.

**Comment by jpmens** [comment] 2024-10-30 08:45
I think the problem is due to `OTR_TOPICS` being an `ENV` configured in the `Dockerfile` and (I'm far from a specialist!) that seems to override whatever else we configure.

I've managed with the following invocation:

```console
docker run -it -p 8083:8083 \
        -e OTR_HOST=192.168.1.30 \
        -e OTR_PORT=1883 \
        -v $(pwd)/r_config:/config \
        -v $(pwd)/r_store:/store \
        --entrypoint /usr/sbin/ot-recorder \
        -e OTR_TOPICS=msh/EU_868/2/json/# \
        owntracks/recorder
```

If I don't specify `OTR_TOPICS` in the environment (`-e`), then the value in `recorder.conf` is used.

Can you adapt that to your compose situation?

**Comment by Th3H0ff** [comment] 2024-10-30 08:55
I've been down these steps. I've updated my docker-compose to

```
  owntrack-backend:
    image: owntracks/recorder
    container_name: owntrack-backend
    ports:
      - 8085:8085
    volumes:
      - /home/owntrack/config:/config
      - /home/owntrack/store:/store
    restart: unless-stopped
    environment:
      - OTR_TOPICS = "msh/EU_868/2/json/HoffChannel/#"
```

But still the log says
+ HTTP listener started on 0.0.0.0:8083, without browser-apikey
+ HTTP prefix is unset
+ Using storage at /store with precision 7
+ Configured with revgeo=true and geokey: nil
+ TZDATADB is at /config/timezone16.bin: ENOENT
+ Subscribing to owntracks/# (qos=2)

**Comment by jpmens** [comment] 2024-10-30 09:12
I do not see where you've overriden the entrypoint: `--entrypoint /usr/sbin/ot-recorder`

**Comment by Th3H0ff** [comment] 2024-10-30 09:44
Where would I do that?

**Comment by jpmens** [comment] 2024-10-30 09:45
Have you tried consulting some documentation on docker compose files?

**Comment by Th3H0ff** [comment] 2024-10-30 10:07
Not really, this would be the first time. I have yet to understand what I'm aiming for?

**Comment by jpmens** [comment] 2024-10-30 10:10
I'm probably not familiar enough with all this, but what we're aiming to do is to override the _entrypoint_ as defined in the Dockerfile which was used during building of the image.

I demonstrated above how that works on the CLI.

You'll want to look at [the documentation for services](https://docs.docker.com/reference/compose-file/services/#entrypoint) in docker compose files to attempt to accomplish the same.

**Comment by Th3H0ff** [comment] 2024-10-30 10:45
Ok, some GPT-help got me this addition to my docker-compose.yml
`entrypoint: ["/usr/sbin/ot-recorder", "msh/EU_868/2/json/HoffChannel/#", "owntracks/#"]`
Now my log gives me
+ Subscribing to msh/EU_868/2/json/HoffChannel/# (qos=2)
+ Subscribing to owntracks/# (qos=2)

A thing I noticed was entrypoint.sh is looking for the variable OTR_TOPIC whereas the documentation at https://github.com/owntracks/recorder?tab=readme-ov-file#configuration-file mentions OTR_TOPICS. For me it doesn't matter since none of the variables has any effect but the entrypoint line in docker-compose has.

**Comment by jpmens** [comment] 2024-10-30 10:53
Ah, good catch. We [merged that change](https://github.com/owntracks/docker-recorder/pull/82) a few months ago, which I had forgotten. I'm not sure that was a typo I didn't catch... 

You might want to go back to your docker-compose and try with the singular:

```
-e OTR_TOPIC=msh/EU_868/2/json/#
```

Glad you got it working.

**Closed** 2024-10-30 13:42 UTC
